-- ============================================
-- Trading Bot Database Schema
-- PostgreSQL Database Tables for Trading Strategies
-- ============================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- 1. CANDLE DATA TABLE
-- Stores 5-minute candle data for all stocks
-- ============================================
CREATE TABLE IF NOT EXISTS candles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    symbol VARCHAR(20) NOT NULL,
    exchange VARCHAR(10) DEFAULT 'NSE',
    timestamp TIMESTAMP NOT NULL,
    open DECIMAL(12, 2) NOT NULL,
    high DECIMAL(12, 2) NOT NULL,
    low DECIMAL(12, 2) NOT NULL,
    close DECIMAL(12, 2) NOT NULL,
    volume BIGINT NOT NULL,
    interval VARCHAR(10) DEFAULT '5min',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(symbol, timestamp, interval)
);

-- Index for faster queries
CREATE INDEX idx_candles_symbol_timestamp ON candles(symbol, timestamp DESC);
CREATE INDEX idx_candles_timestamp ON candles(timestamp DESC);

-- ============================================
-- 2. STRONG MEAN REVERSION SIGNALS TABLE
-- Stores signals generated by Mean Reversion strategy
-- ============================================
CREATE TABLE IF NOT EXISTS mean_reversion_signals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    symbol VARCHAR(20) NOT NULL,
    name VARCHAR(100),
    signal_type VARCHAR(10) NOT NULL CHECK (signal_type IN ('BUY', 'SELL')),
    
    -- Entry details
    entry_price DECIMAL(12, 2) NOT NULL,
    entry_time TIMESTAMP NOT NULL,
    
    -- Technical indicators at entry
    rsi DECIMAL(5, 2),
    bb_upper DECIMAL(12, 2),
    bb_middle DECIMAL(12, 2),
    bb_lower DECIMAL(12, 2),
    ema_value DECIMAL(12, 2),
    ema_period INTEGER,
    volume_ratio DECIMAL(5, 2),
    
    -- Risk management
    stop_loss DECIMAL(12, 2) NOT NULL,
    target DECIMAL(12, 2) NOT NULL,
    risk_amount DECIMAL(12, 2),
    reward_amount DECIMAL(12, 2),
    risk_reward_ratio DECIMAL(5, 2),
    
    -- Exit details
    exit_price DECIMAL(12, 2),
    exit_time TIMESTAMP,
    exit_reason VARCHAR(50), -- 'TARGET_HIT', 'STOP_LOSS', 'MANUAL', 'EOD'
    
    -- P&L
    profit_loss DECIMAL(12, 2),
    profit_loss_percent DECIMAL(5, 2),
    
    -- Status
    status VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'CLOSED', 'CANCELLED')),
    
    -- Metadata
    index_name VARCHAR(20), -- 'nifty50', 'nifty100', 'nifty500'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX idx_mean_reversion_symbol ON mean_reversion_signals(symbol);
CREATE INDEX idx_mean_reversion_status ON mean_reversion_signals(status);
CREATE INDEX idx_mean_reversion_entry_time ON mean_reversion_signals(entry_time DESC);
CREATE INDEX idx_mean_reversion_signal_type ON mean_reversion_signals(signal_type);

-- ============================================
-- 3. SWING TRADING SIGNALS TABLE
-- Stores signals for swing trading (52-week high momentum)
-- ============================================
CREATE TABLE IF NOT EXISTS swing_signals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    symbol VARCHAR(20) NOT NULL,
    name VARCHAR(100),
    
    -- Entry details
    entry_price DECIMAL(12, 2) NOT NULL,
    entry_date DATE NOT NULL,
    entry_time TIMESTAMP NOT NULL,
    
    -- Stock fundamentals at entry
    week_52_high DECIMAL(12, 2),
    week_52_low DECIMAL(12, 2),
    distance_from_52w_high_percent DECIMAL(5, 2),
    volume BIGINT,
    avg_volume_20 BIGINT,
    volume_ratio DECIMAL(5, 2),
    
    -- Risk management
    stop_loss DECIMAL(12, 2) NOT NULL,
    stop_loss_type VARCHAR(20), -- 'PERCENTAGE', 'TECHNICAL', 'SWING_LOW'
    target_1 DECIMAL(12, 2),
    target_2 DECIMAL(12, 2),
    target_3 DECIMAL(12, 2),
    
    -- Exit details
    exit_price DECIMAL(12, 2),
    exit_date DATE,
    exit_time TIMESTAMP,
    exit_reason VARCHAR(50),
    holding_days INTEGER,
    
    -- P&L
    profit_loss DECIMAL(12, 2),
    profit_loss_percent DECIMAL(5, 2),
    
    -- Partial exits
    partial_exit_1_price DECIMAL(12, 2),
    partial_exit_1_time TIMESTAMP,
    partial_exit_1_percent INTEGER, -- Percentage of position exited
    partial_exit_2_price DECIMAL(12, 2),
    partial_exit_2_time TIMESTAMP,
    partial_exit_2_percent INTEGER,
    
    -- Status
    status VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'PARTIAL', 'CLOSED', 'CANCELLED')),
    
    -- Metadata
    source VARCHAR(50) DEFAULT 'CHARTINK', -- 'CHARTINK', 'MANUAL', 'SCANNER'
    sector VARCHAR(50),
    market_cap VARCHAR(20), -- 'LARGE', 'MID', 'SMALL'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX idx_swing_symbol ON swing_signals(symbol);
CREATE INDEX idx_swing_status ON swing_signals(status);
CREATE INDEX idx_swing_entry_date ON swing_signals(entry_date DESC);
CREATE INDEX idx_swing_source ON swing_signals(source);

-- ============================================
-- 4. ORB (Opening Range Breakout) SIGNALS TABLE
-- Stores signals for ORB strategy
-- ============================================
CREATE TABLE IF NOT EXISTS orb_signals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    symbol VARCHAR(20) NOT NULL,
    name VARCHAR(100),
    trade_date DATE NOT NULL,
    
    -- Opening range (9:15-9:30 AM)
    orb_high DECIMAL(12, 2) NOT NULL,
    orb_low DECIMAL(12, 2) NOT NULL,
    orb_open DECIMAL(12, 2),
    orb_close DECIMAL(12, 2),
    orb_range DECIMAL(12, 2), -- orb_high - orb_low
    orb_range_percent DECIMAL(5, 2), -- (range / orb_open) * 100
    
    -- Breakout details
    breakout_type VARCHAR(10) CHECK (breakout_type IN ('BULLISH', 'BEARISH')),
    breakout_time TIMESTAMP,
    breakout_price DECIMAL(12, 2),
    breakout_volume BIGINT,
    
    -- Entry details
    entry_price DECIMAL(12, 2) NOT NULL,
    entry_time TIMESTAMP NOT NULL,
    
    -- Risk management
    stop_loss DECIMAL(12, 2) NOT NULL,
    target DECIMAL(12, 2) NOT NULL,
    risk_amount DECIMAL(12, 2),
    reward_amount DECIMAL(12, 2),
    risk_reward_ratio DECIMAL(5, 2),
    
    -- Exit details
    exit_price DECIMAL(12, 2),
    exit_time TIMESTAMP,
    exit_reason VARCHAR(50),
    
    -- P&L
    profit_loss DECIMAL(12, 2),
    profit_loss_percent DECIMAL(5, 2),
    
    -- Trade duration
    holding_minutes INTEGER,
    
    -- Status
    status VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'CLOSED', 'CANCELLED')),
    
    -- Quality metrics
    false_breakout BOOLEAN DEFAULT FALSE,
    immediate_reversal BOOLEAN DEFAULT FALSE,
    
    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    UNIQUE(symbol, trade_date)
);

-- Indexes
CREATE INDEX idx_orb_symbol ON orb_signals(symbol);
CREATE INDEX idx_orb_trade_date ON orb_signals(trade_date DESC);
CREATE INDEX idx_orb_status ON orb_signals(status);
CREATE INDEX idx_orb_breakout_type ON orb_signals(breakout_type);

-- ============================================
-- 5. STRATEGY PERFORMANCE TABLE
-- Tracks overall performance metrics for each strategy
-- ============================================
CREATE TABLE IF NOT EXISTS strategy_performance (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    strategy_name VARCHAR(50) NOT NULL,
    date DATE NOT NULL,
    
    -- Trade statistics
    total_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    breakeven_trades INTEGER DEFAULT 0,
    
    -- Win rate
    win_rate DECIMAL(5, 2),
    
    -- P&L
    total_profit DECIMAL(12, 2) DEFAULT 0,
    total_loss DECIMAL(12, 2) DEFAULT 0,
    net_profit_loss DECIMAL(12, 2) DEFAULT 0,
    
    -- Average metrics
    avg_profit DECIMAL(12, 2),
    avg_loss DECIMAL(12, 2),
    avg_profit_percent DECIMAL(5, 2),
    avg_loss_percent DECIMAL(5, 2),
    
    -- Risk metrics
    largest_win DECIMAL(12, 2),
    largest_loss DECIMAL(12, 2),
    profit_factor DECIMAL(5, 2), -- total_profit / total_loss
    
    -- Holding period
    avg_holding_period_minutes INTEGER,
    
    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    UNIQUE(strategy_name, date)
);

-- Indexes
CREATE INDEX idx_performance_strategy ON strategy_performance(strategy_name);
CREATE INDEX idx_performance_date ON strategy_performance(date DESC);

-- ============================================
-- 6. TRADE JOURNAL TABLE
-- Manual notes and observations for each trade
-- ============================================
CREATE TABLE IF NOT EXISTS trade_journal (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    signal_id UUID NOT NULL,
    strategy_name VARCHAR(50) NOT NULL,
    
    -- Journal entry
    entry_notes TEXT,
    exit_notes TEXT,
    lessons_learned TEXT,
    
    -- Market conditions
    market_sentiment VARCHAR(20), -- 'BULLISH', 'BEARISH', 'NEUTRAL', 'CHOPPY'
    market_trend VARCHAR(20), -- 'UPTREND', 'DOWNTREND', 'SIDEWAYS'
    
    -- Emotional state
    emotional_state VARCHAR(20), -- 'CONFIDENT', 'FEARFUL', 'GREEDY', 'NEUTRAL'
    
    -- Mistakes made
    mistakes TEXT,
    
    -- Rating
    trade_quality_rating INTEGER CHECK (trade_quality_rating BETWEEN 1 AND 5),
    
    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX idx_journal_signal_id ON trade_journal(signal_id);
CREATE INDEX idx_journal_strategy ON trade_journal(strategy_name);

-- ============================================
-- 7. MARKET CONDITIONS TABLE
-- Stores daily market conditions for context
-- ============================================
CREATE TABLE IF NOT EXISTS market_conditions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    date DATE NOT NULL UNIQUE,
    
    -- Index data
    nifty50_open DECIMAL(10, 2),
    nifty50_high DECIMAL(10, 2),
    nifty50_low DECIMAL(10, 2),
    nifty50_close DECIMAL(10, 2),
    nifty50_change_percent DECIMAL(5, 2),
    
    -- Market metrics
    advance_decline_ratio DECIMAL(5, 2),
    total_volume BIGINT,
    
    -- Volatility
    vix_value DECIMAL(5, 2),
    
    -- Market type
    market_type VARCHAR(20), -- 'TRENDING', 'RANGE_BOUND', 'VOLATILE', 'QUIET'
    
    -- News/Events
    major_events TEXT,
    
    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index
CREATE INDEX idx_market_conditions_date ON market_conditions(date DESC);

-- ============================================
-- 8. STOCK WATCHLIST TABLE
-- Stocks being monitored for potential signals
-- ============================================
CREATE TABLE IF NOT EXISTS watchlist (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    symbol VARCHAR(20) NOT NULL,
    name VARCHAR(100),
    strategy_name VARCHAR(50) NOT NULL,
    
    -- Why it's on watchlist
    reason TEXT,
    
    -- Alert levels
    alert_price_above DECIMAL(12, 2),
    alert_price_below DECIMAL(12, 2),
    
    -- Status
    is_active BOOLEAN DEFAULT TRUE,
    
    -- Metadata
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    removed_at TIMESTAMP,
    
    UNIQUE(symbol, strategy_name)
);

-- Indexes
CREATE INDEX idx_watchlist_symbol ON watchlist(symbol);
CREATE INDEX idx_watchlist_strategy ON watchlist(strategy_name);
CREATE INDEX idx_watchlist_active ON watchlist(is_active);

-- ============================================
-- VIEWS FOR EASY QUERYING
-- ============================================

-- View: Active Mean Reversion Signals
CREATE OR REPLACE VIEW v_active_mean_reversion AS
SELECT 
    id,
    symbol,
    name,
    signal_type,
    entry_price,
    entry_time,
    stop_loss,
    target,
    risk_reward_ratio,
    rsi,
    status
FROM mean_reversion_signals
WHERE status = 'ACTIVE'
ORDER BY entry_time DESC;

-- View: Active Swing Signals
CREATE OR REPLACE VIEW v_active_swing AS
SELECT 
    id,
    symbol,
    name,
    entry_price,
    entry_date,
    stop_loss,
    target_1,
    target_2,
    target_3,
    holding_days,
    status
FROM swing_signals
WHERE status IN ('ACTIVE', 'PARTIAL')
ORDER BY entry_date DESC;

-- View: Active ORB Signals
CREATE OR REPLACE VIEW v_active_orb AS
SELECT 
    id,
    symbol,
    name,
    trade_date,
    breakout_type,
    entry_price,
    stop_loss,
    target,
    risk_reward_ratio,
    status
FROM orb_signals
WHERE status = 'ACTIVE'
ORDER BY trade_date DESC, entry_time DESC;

-- View: Daily Performance Summary
CREATE OR REPLACE VIEW v_daily_performance AS
SELECT 
    strategy_name,
    date,
    total_trades,
    winning_trades,
    losing_trades,
    win_rate,
    net_profit_loss,
    profit_factor
FROM strategy_performance
ORDER BY date DESC, strategy_name;

-- ============================================
-- FUNCTIONS
-- ============================================

-- Function: Update strategy performance
CREATE OR REPLACE FUNCTION update_strategy_performance()
RETURNS TRIGGER AS $$
BEGIN
    -- This function can be called after a signal is closed
    -- to update the strategy_performance table
    -- Implementation depends on specific requirements
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Function: Calculate holding period
CREATE OR REPLACE FUNCTION calculate_holding_period()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.exit_time IS NOT NULL AND NEW.entry_time IS NOT NULL THEN
        NEW.holding_minutes := EXTRACT(EPOCH FROM (NEW.exit_time - NEW.entry_time)) / 60;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger: Update holding period for ORB signals
CREATE TRIGGER trg_orb_holding_period
BEFORE UPDATE ON orb_signals
FOR EACH ROW
WHEN (NEW.exit_time IS NOT NULL)
EXECUTE FUNCTION calculate_holding_period();

-- Function: Update timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers: Update updated_at on all signal tables
CREATE TRIGGER trg_mean_reversion_updated_at
BEFORE UPDATE ON mean_reversion_signals
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_swing_updated_at
BEFORE UPDATE ON swing_signals
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_orb_updated_at
BEFORE UPDATE ON orb_signals
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- SAMPLE QUERIES (Commented)
-- ============================================

/*
-- Get all active signals across all strategies
SELECT 'Mean Reversion' as strategy, symbol, entry_price, entry_time as time
FROM mean_reversion_signals WHERE status = 'ACTIVE'
UNION ALL
SELECT 'Swing' as strategy, symbol, entry_price, entry_time as time
FROM swing_signals WHERE status IN ('ACTIVE', 'PARTIAL')
UNION ALL
SELECT 'ORB' as strategy, symbol, entry_price, entry_time as time
FROM orb_signals WHERE status = 'ACTIVE'
ORDER BY time DESC;

-- Get today's performance for all strategies
SELECT * FROM v_daily_performance
WHERE date = CURRENT_DATE;

-- Get win rate for each strategy (last 30 days)
SELECT 
    strategy_name,
    AVG(win_rate) as avg_win_rate,
    SUM(total_trades) as total_trades,
    SUM(net_profit_loss) as total_pnl
FROM strategy_performance
WHERE date >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY strategy_name;

-- Get best performing stocks (last 30 days)
SELECT 
    symbol,
    COUNT(*) as trades,
    SUM(CASE WHEN profit_loss > 0 THEN 1 ELSE 0 END) as wins,
    AVG(profit_loss_percent) as avg_return
FROM mean_reversion_signals
WHERE entry_time >= CURRENT_DATE - INTERVAL '30 days'
    AND status = 'CLOSED'
GROUP BY symbol
HAVING COUNT(*) >= 3
ORDER BY avg_return DESC
LIMIT 10;
*/

-- ============================================
-- END OF SCHEMA
-- ============================================

-- Made with Bob
